name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t registry.internal.com:30500/bank-frontend-test .

      - name: Log in to registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login registry.internal.com:30500 -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to registry
        run: docker push registry.internal.com:30500/bank-frontend-test
